services:
  - type: web
    name: quick-study-test-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: DB_PATH
        value: data.db
